title: Jessica Castrillon Lal, PhD
#logo: /path_to_image.png
desription: Post-doctoral Fellow @ MD Anderson Cancer Center
Wenyi Wang Lab| Bioinformatics & Computational Biology
Kopetz Lab| Gastrointestinal Medical Oncology
show_downloads: true
theme: jekyll-theme-minima
