title: Jessica Castrillon Lal, PhD
logo: /portfolio/296549_Lal_J.jpg
desription: Post-doctoral Fellow @ MD Anderson Cancer Center
#Wenyi Wang Lab| Bioinformatics & Computational Biology
#Kopetz Lab| Gastrointestinal Medical Oncology
show_downloads: true
theme: jekyll-theme-minimal
